DROP TABLE IF EXISTS AMS_USER_LOGIN;

CREATE TABLE AMS_USER_LOGIN(
	USER_ID INT NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(500) NOT NULL,
	USER_PASSWORD VARCHAR(500) NOT NULL,
	USER_PAN_CARD VARCHAR(500) NOT NULL,
	CONSTRAINT AMS_USER_LOGIN_PK PRIMARY KEY(USER_ID)
);

DROP TABLE IF EXISTS AMS_ENTITLEMENT;

CREATE TABLE AMS_ENTITLEMENT(
	ENTITLEMENT_ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	ENTITLEMENT_TYPE VARCHAR(200) NOT NULL,
	CONSTRAINT AMS_ENTITLEMENT_PK PRIMARY KEY(ENTITLEMENT_ID),
	CONSTRAINT AMS_ENTITLEMENT_FK1 FOREIGN KEy (USER_ID) REFERENCES AMS_USER_LOGIN(USER_ID)
);

